Repository weeklyJisimi/jinsim-front, pull requests merged in 2024-07, with the labels that each got.

#2 [SETTING] 기본 이슈 템플릿들 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ⚙️ SETTING

#3 [SETTING] 프로젝트 초기 설정
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-test.yml
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  next.config.mjs
  package-lock.json
  package.json
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/providers/chakraProvider.tsx
  src/providers/queryClientProvider.tsx
  tsconfig.json
Labels: ⚙️ SETTING

#5 [로그인] 임시 로그인 페이지와 임시 기본 페이지 레이아웃 구성
  src/app/layout.tsx
  src/app/login/kakaoLoginButton.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/component/icon/kakaoSymbol.tsx
  src/component/layout/header.tsx
  src/component/layout/mainLayout.tsx
Labels: 🎨 DESIGN

#20 [편지] 초기 생성 페이지
  package-lock.json
  package.json
  src/app/letter/@create/layout.tsx
  src/app/letter/@create/loading.tsx
  src/app/letter/@create/page.tsx
  src/app/letter/@initial/page.tsx
  src/app/letter/layout.tsx
  src/app/letter/letter-flow-store.ts
  src/app/letter/letter-source-store.tsx
  src/app/letter/page.tsx
  src/component/common/jinsimi.tsx
Labels: 🛠️ FEATURE

#22 [편지] 초기 생성 페이지 수정
  src/app/letter/@create/page.tsx
  src/app/letter/@initial/page.tsx
  src/app/letter/@initial/question.ts
  src/app/letter/letter-source-store.tsx
Labels: 🛠️ FEATURE

#24 [로그인/메인] 문체수집, 메인페이지 (UI만)
  package-lock.json
  src/app/calender/page.tsx
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/setting/inquiry/page.tsx
  src/app/setting/notice/page.tsx
  src/app/setting/subscribe/page.tsx
  src/app/view/[id]/page.tsx
  src/app/view/page.tsx
  src/component/layout/mainLayout.tsx
  src/component/layout/mainPageLayout.tsx
Labels: 🛠️ FEATURE

#29 [편지] 편지 가져오고 저장하기 페이지
  src/app/letter/@create/page.tsx
  src/app/letter/letter-store.ts
Labels: 🛠️ FEATURE

#32 [Login] 카카오 Oauth 추가 (API 연결 없음) (#6)
  .github/workflows/build-test.yml
  .gitignore
  package-lock.json
  package.json
  src/app/intro/layout.tsx
  src/app/intro/page.tsx
  src/app/login/kakaoLoginButton.tsx
  src/app/login/page.tsx
Labels: 🛠️ FEATURE

#36 [편지] 편지함 디테일 페이지
  package-lock.json
  package.json
  src/app/letter/view/[id]/page.tsx
  src/app/letter/view/page.tsx
  src/component/common/shareLetter.tsx
  src/component/layout/header.tsx
  src/component/layout/mainPageLayout.tsx
Labels: 🛠️ FEATURE

#38 [편지] 임시저장 편지 페이지
  src/app/letter/@create/page.tsx
  src/app/letter/layout.tsx
  src/app/letter/letter-store.ts
  src/app/page.tsx
Labels: 🛠️ FEATURE

#44 [편지] 편지 생성 페이지 디자인
  package-lock.json
  package.json
  src/app/letter/@create/loading.tsx
  src/app/letter/@create/page.tsx
  src/app/letter/@initial/page.tsx
  src/app/letter/page.tsx
  src/component/common/FairyJinsimi.tsx
  src/component/common/fairy.json
Labels: 🎨 DESIGN

#47 [메인] 메인 페이지 디자인
  public/jinsimi.png
  public/logo.png
  public/mainBackground.png
  src/app/page.tsx
  src/component/layout/mainPageLayout.tsx
Labels: 🎨 DESIGN

#49 [편지] 편지 저장 직전까지 api 연결
  src/app/intro/page.tsx
  src/app/letter/@create/page.tsx
  src/app/letter/@initial/page.tsx
  src/app/letter/@initial/question.ts
  src/app/letter/letter-source-store.tsx
  src/app/letter/letter-store.ts
  src/app/letter/style_characteristics.ts
Labels: 💫 API

#51 [편지] 진입 안내 메시지 추가
  src/app/letter/page.tsx
Labels: 🎨 DESIGN
